# Generated by Django 5.1.5 on 2026-03-01 08:47

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='display_image',
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[1200, 1500], upload_to='collections/%Y/'),
        ),
    ]
