# Generated by Django 6.0.2 on 2026-03-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_address_order_city_order_full_name_order_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1_word1', models.CharField(blank=True, max_length=9, null=True)),
                ('heading1_word2', models.CharField(blank=True, max_length=9, null=True)),
                ('subheading1', models.CharField(max_length=40)),
                ('subheading2', models.CharField(max_length=20)),
                ('heading2', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Landing Page Configuration',
                'verbose_name_plural': 'Landing Page Configuration',
            },
        ),
    ]
