# Generated by Django 6.0.2 on 2026-03-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_landingpageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='button1_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='button2_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
