# Generated by Django 6.0.2 on 2026-03-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_landingpageconfig_button1_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheading1', models.CharField(blank=True, max_length=20, null=True)),
                ('heading1', models.CharField(blank=True, max_length=15, null=True)),
                ('subheading2', models.CharField(blank=True, max_length=20, null=True)),
                ('paragraph1', models.CharField(blank=True, max_length=100, null=True)),
                ('heading2_word1', models.CharField(blank=True, max_length=10, null=True)),
                ('heading2_word2', models.CharField(blank=True, max_length=10, null=True)),
                ('paragraph2', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph3', models.CharField(blank=True, max_length=100, null=True)),
                ('heading3', models.CharField(blank=True, max_length=20, null=True)),
                ('subheading3', models.CharField(blank=True, max_length=100, null=True)),
                ('subheading4', models.CharField(blank=True, max_length=100, null=True)),
                ('heading4', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'our story Page Configuration',
                'verbose_name_plural': 'our story Page Configuration',
            },
        ),
    ]
