# Generated by Django 6.0.2 on 2026-03-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='KAVRA Luxury Apparel', max_length=100)),
                ('support_email', models.EmailField(default='concierge@kavra.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('international_shipping', models.BooleanField(default=True)),
                ('announcement_banner', models.CharField(default='Complimentary Express Shipping.', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
