# Generated by Django 6.0.2 on 2026-03-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageconfig',
            name='heading2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='landingpageconfig',
            name='subheading1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='landingpageconfig',
            name='subheading2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
