# Generated by Django 6.0.2 on 2026-03-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_landingpageconfig_heading2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-id']},
        ),
    ]
