# Generated by Django 6.0.2 on 2026-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Site_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Email_app_code', models.CharField(max_length=20)),
            ],
        ),
    ]
