# Generated by Django 6.0.2 on 2026-03-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genralsettings',
            name='Instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genralsettings',
            name='contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='genralsettings',
            name='Email_app_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
